name = "HeckeAlgebra"
version = "0.1.0"
defaultTargets = ["heckealgebra"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0-rc1"

[[lean_lib]]
name = "HeckeAlgebra"

[[lean_exe]]
name = "heckealgebra"
root = "Main"
